/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jplus.compare.excel.frame;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.jplus.compare.excel.db.SqliteDao;
import org.jplus.compare.excel.model.DataRowModel;
import org.jplus.hyb.database.sqlite.SqliteUtil;
import org.jplus.compare.excel.bean.OptionBean;
import org.jplus.compare.excel.service.CompareService;

/**
 *
 * @author hyberbin
 */
public class CompareFrame extends javax.swing.JFrame {

    private final List<String> columns;
    private final List<String> allcolumns;
    private final List<String> problemColumns;
    private final String[] columnsArray;
    private final OptionFrame optionFrame;
    private final List<Map> currentMap;
    private List<Map> lastMap;

    /** Creates new form CompareFrame */
    public CompareFrame(List<String> allcolumns,List<String> columns, OptionFrame optionFrame) {
        columns.add(0,SqliteUtil.getProperty("cellKey"));
        columns.add(1,SqliteUtil.getProperty("nameKey"));
        this.columns = columns;
        this.allcolumns=allcolumns;
        problemColumns=new ArrayList<String>(columns);
        problemColumns.add("相差值");
        this.optionFrame = optionFrame;
        columnsArray = columns.toArray(new String[]{});
        initComponents();
        DataRowModel model = (DataRowModel) jTable1.getModel();
        currentMap = CompareService.getExcelContent(optionFrame.getCurrentExcelPath(),SqliteUtil.getProperty("currentSheetName"));
        model.addRow(currentMap);
        Toolkit tk = Toolkit.getDefaultToolkit();
        setLocation((tk.getScreenSize().width - getSize().width) / 2,
                (tk.getScreenSize().height - getSize().height) / 2);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                if (JOptionPane.showConfirmDialog(null, "确认退出？") == 0) {
                    dispose();
                    System.exit(0);
                }
            }
        });
    }

    /** This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new DataRowModel(columns));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("待比较表格", jScrollPane1);

        jTable2.setModel(new DataRowModel(problemColumns));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("有问题的行", jScrollPane2);

        jButton1.setText("上一步");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("比较");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lastMap = CompareService.getExcelContent(optionFrame.getLastExcelPath(),SqliteUtil.getProperty("lastSheetName"));
        Map<String,OptionBean> optionMap=new HashMap<String, OptionBean>();
        List<OptionBean> all = SqliteDao.getAll(OptionBean.class);
        for (OptionBean optionBean : all) {
            if(optionBean.getCompare()){
                optionMap.put(optionBean.getItemName(), optionBean);
            }
        }
        List<Map> compare = CompareService.compare(CompareService.getSalaryMap(lastMap,SqliteUtil.getProperty("cellKey")), CompareService.getSalaryMap(currentMap,SqliteUtil.getProperty("cellKey")), columnsArray, optionMap);
        DataRowModel model = (DataRowModel) jTable2.getModel();
        model.addRow(compare);
        jTabbedPane1.setSelectedIndex(1);
        JOptionPane.showMessageDialog(rootPane,"比较完毕"+ (model.getRowCount()>0?"标记过的文件生成在:标记过的Excel.xls":"两个文件一致!"));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       optionFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
